name: api.pr.qualifica.mobi
on:
  issue_comment:
    types: [created]
        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy-pr')

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
    - name: Checkout PR
      run: |
        git init
        git fetch --depth=1 origin "refs/pull/${{ github.event.issue.number }}/head"
        git checkout -b pr-${{ github.event.issue.number }} FETCH_HEAD
        
   

    - name: Print variable from Doppler 
      run: ls -la
