name: api.pr.qualifica.mobi
on:
  issue_comment:
    types: [created]
        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy-pr')

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.issue.pull_request.head.sha }}
        
   

    - name: Print variable from Doppler 
      run: ls -la
