name: api.pr.qualifica.mobi
on:
  issue_comment:
    types: [created]
        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy-pr')

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
    - name: Get PR details
      id: pr-details
      run: |
        echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"
        echo "::set-output name=pr_sha::$(curl -s -H "Authorization: Bearer ${{ secrets.ABGITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" | jq -r .head.sha)"
        
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: "pull/${{ steps.pr-details.outputs.pr_number}}/head"
        
   

    - name: Print variable from Doppler 
      run: ls -la
