name: api.pr.qualifica.mobi
on:
  issue_comment:
    types: [created]
        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy-pr')

    strategy:
      matrix:
        node-version: [12.13.0]


    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
        
   

      - name: Print variable from Doppler 
        run: ls -la
